# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreenByMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'
  pod 'Alamofire'
  pod 'Kingfisher'
  # Pods for GreenByMe

  target 'GreenByMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GreenByMeUITests' do
    # Pods for testing
  end

end
