# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'greenByMe2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'PKHUD', '~> 5.0'

  # Pods for greenByMe2

  target 'greenByMe2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'greenByMe2UITests' do
    # Pods for testing
  end

end
